"""
Database models for trades, markets, wallets, and signals.
SQLAlchemy async ORM with SQLite/Postgres support.
"""

from datetime import datetime
from typing import Optional
from sqlalchemy import (
    Column, String, Float, Integer, Boolean, DateTime,
    JSON, Text, Enum as SQLEnum, ForeignKey, Index
)
from sqlalchemy.orm import DeclarativeBase, relationship
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession, async_sessionmaker
import enum

from polybotking.config import settings


class Base(DeclarativeBase):
    pass


# --- Enums ---

class TradeStatus(enum.Enum):
    PENDING = "pending"
    OPEN = "open"
    FILLED = "filled"
    PARTIAL = "partial"
    CLOSED = "closed"
    CANCELLED = "cancelled"


class SignalType(enum.Enum):
    MISPRICING = "mispricing"
    ARBITRAGE = "arbitrage"
    SENTIMENT = "sentiment"
    VOLATILITY = "volatility"
    WALLET_FOLLOW = "wallet_follow"
    COMBINED = "combined"


class MarketStatus(enum.Enum):
    ACTIVE = "active"
    RESOLVED = "resolved"
    PAUSED = "paused"


# --- Models ---

class Market(Base):
    """Polymarket market/event tracking."""
    __tablename__ = "markets"

    id = Column(String, primary_key=True)
    condition_id = Column(String, index=True)
    question = Column(Text, nullable=False)
    category = Column(String, default="")
    end_date = Column(DateTime, nullable=True)
    status = Column(SQLEnum(MarketStatus), default=MarketStatus.ACTIVE)

    # Pricing
    yes_price = Column(Float, default=0.5)
    no_price = Column(Float, default=0.5)
    spread = Column(Float, default=0.0)
    volume_24h = Column(Float, default=0.0)
    liquidity = Column(Float, default=0.0)

    # Analysis
    true_probability = Column(Float, nullable=True)
    edge = Column(Float, nullable=True)
    ev_score = Column(Float, nullable=True)
    sentiment_score = Column(Float, nullable=True)
    volatility_score = Column(Float, nullable=True)

    # Metadata
    last_scanned = Column(DateTime, default=datetime.utcnow)
    created_at = Column(DateTime, default=datetime.utcnow)
    raw_data = Column(JSON, default=dict)

    trades = relationship("Trade", back_populates="market")

    __table_args__ = (
        Index("idx_market_edge", "edge"),
        Index("idx_market_status_end", "status", "end_date"),
    )


class Trade(Base):
    """Individual trade/position record."""
    __tablename__ = "trades"

    id = Column(Integer, primary_key=True, autoincrement=True)
    market_id = Column(String, ForeignKey("markets.id"), index=True)
    order_id = Column(String, nullable=True)

    # Trade details
    side = Column(String, nullable=False)  # YES / NO
    entry_price = Column(Float, nullable=False)
    exit_price = Column(Float, nullable=True)
    size = Column(Float, nullable=False)
    cost = Column(Float, nullable=False)
    pnl = Column(Float, nullable=True)

    # Signal info
    signal_type = Column(SQLEnum(SignalType), default=SignalType.COMBINED)
    confidence = Column(Float, default=0.5)
    kelly_size = Column(Float, nullable=True)
    edge_at_entry = Column(Float, nullable=True)

    # Status
    status = Column(SQLEnum(TradeStatus), default=TradeStatus.PENDING)
    entry_time = Column(DateTime, default=datetime.utcnow)
    exit_time = Column(DateTime, nullable=True)

    # Metadata
    notes = Column(Text, default="")
    raw_data = Column(JSON, default=dict)

    market = relationship("Market", back_populates="trades")

    __table_args__ = (
        Index("idx_trade_status", "status"),
        Index("idx_trade_pnl", "pnl"),
    )


class WalletProfile(Base):
    """Tracked wallet intelligence profile."""
    __tablename__ = "wallet_profiles"

    address = Column(String, primary_key=True)
    label = Column(String, default="unknown")

    # Performance
    total_trades = Column(Integer, default=0)
    win_rate = Column(Float, default=0.0)
    total_pnl = Column(Float, default=0.0)
    avg_position_size = Column(Float, default=0.0)
    avg_hold_time_hours = Column(Float, default=0.0)

    # Patterns
    preferred_categories = Column(JSON, default=list)
    size_pattern = Column(String, default="unknown")  # small/medium/large/whale
    timing_pattern = Column(String, default="unknown")  # early/mid/late
    cluster_id = Column(Integer, nullable=True)

    # Metadata
    last_active = Column(DateTime, nullable=True)
    first_seen = Column(DateTime, default=datetime.utcnow)
    confidence_score = Column(Float, default=0.0)
    raw_data = Column(JSON, default=dict)

    __table_args__ = (
        Index("idx_wallet_winrate", "win_rate"),
        Index("idx_wallet_cluster", "cluster_id"),
    )


class Signal(Base):
    """Trading signal generated by engines."""
    __tablename__ = "signals"

    id = Column(Integer, primary_key=True, autoincrement=True)
    market_id = Column(String, ForeignKey("markets.id"), index=True)
    signal_type = Column(SQLEnum(SignalType), nullable=False)

    # Signal data
    direction = Column(String, nullable=False)  # YES / NO
    confidence = Column(Float, nullable=False)
    edge = Column(Float, nullable=False)
    ev = Column(Float, nullable=False)
    recommended_size = Column(Float, nullable=True)

    # Context
    reasoning = Column(Text, default="")
    source_data = Column(JSON, default=dict)

    # Status
    acted_upon = Column(Boolean, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    expires_at = Column(DateTime, nullable=True)

    __table_args__ = (
        Index("idx_signal_ev", "ev"),
        Index("idx_signal_type_time", "signal_type", "created_at"),
    )


class BotState(Base):
    """Bot runtime state persistence."""
    __tablename__ = "bot_state"

    key = Column(String, primary_key=True)
    value = Column(JSON, nullable=False)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)


# --- Database Session ---

# Ensure `data/` directory exists for the default sqlite path BEFORE creating
# the engine. Settings.__init__ also calls this, but be defensive in case the
# database URL was changed via env var to another sqlite file under ./data.
_ = settings.data_dir

engine = create_async_engine(settings.database.url, echo=False)
async_session = async_sessionmaker(engine, class_=AsyncSession, expire_on_commit=False)


async def init_db() -> None:
    """Initialize database tables."""
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)


async def get_session():
    """Get a database session (async generator)."""
    async with async_session() as session:
        yield session
